### ISSUE TITLE
Solution does not work when copying an image with data:image/ 

### ISSUE THREAD

**Issue by krptodr** [DevExpress-Examples/aspxhtmleditor-how-to-process-images-from-base64-strings-t223166#1]
It seems this solution is no longer working. Can we provide a fix?

**Comment by mpreyskurantov** [comment]
It is likely that the image was not saved because the required destination server folder did not exist. I have corrected this and now this issue should be resolved. So, you can test in online.
When pasting a base64 image, make sure that its content (&lt;img src="data:image/png;base64,..." /&gt;) does not contain line breaks and is w3c compliant. If you still have troubles with this solution, please create a new ticket in our Support Center, describe your scenario in greater detail, and provide the related raw html base64 image used for testing. We will do our best to guide you.
